Repository hashmaster3k/futbol, pull requests merged in 2020-07, with the labels that each got.

#11 i1-game teams
  lib/game_team.rb
  lib/game_teams_collection.rb
  test/fixtures/game_teams.csv
  test/game_team_test.rb
  test/game_teams_collection_test.rb
Labels: New Class

#18 i1-game teams collection
  lib/game_teams_collection.rb
  test/fixtures/games_teams.csv
  test/game_teams_collection_test.rb
Labels: New Class

#28 i1-stat tracker
  lib/game_teams_collection.rb
  lib/games_collection.rb
  lib/stat_tracker.rb
  runner.rb
Labels: New Class

#53 I2 highest total score
  lib/game.rb
  lib/game_statistics.rb
  lib/stat_tracker.rb
  lib/teams_collection.rb
  test/game_statistics_test.rb
Labels: New Class, New Method

#54 Add game stats game goals helper test
  test/game_statistics_test.rb
Labels: enhancement

#55 i2-season statistics
  lib/season_statistics.rb
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: New Class, New Method

#56 I2 high score test
  lib/game_teams_collection.rb
  lib/games_collection.rb
  lib/teams_collection.rb
  test/game_statistics_test.rb
Labels: enhancement

#58 I2 percent home wins
  lib/game_statistics.rb
  test/game_statistics_test.rb
Labels: New Method

#63 I2 count games by season
  lib/game_statistics.rb
  test/game_statistics_test.rb
Labels: New Method

#59 It2 league stats
  lib/league_statistics.rb
  test/league_statistics_test.rb
Labels: New Method

#65 i2-team info
  lib/team_statistics.rb
  test/team_statistics_test.rb
Labels: New Class, New Method

#69 i2-best season
  lib/team_statistics.rb
  test/team_statistics_test.rb
Labels: New Method

#67 Add league stats lowest scoring visitor test and method
  lib/league_statistics.rb
  test/league_statistics_test.rb
Labels: New Method

#66 Add league statistics include in stat tracker
  lib/stat_tracker.rb
Labels: bug

#73 i2-fewest goals
  lib/team_statistics.rb
  test/team_statistics_test.rb
Labels: New Method

#74 i2-average_win_percentage
  lib/team_statistics.rb
  test/team_statistics_test.rb
Labels: New Method

#72 i2-average goals per game
  lib/game_statistics.rb
  test/game_statistics_test.rb
Labels: New Method

#78 collections class fixes
  test/game_teams_collection_test.rb
  test/games_collection_test.rb
  test/teams_collection_test.rb
Labels: bug

#79 It2 teamstats favorite opponent
  lib/team_statistics.rb
  test/team_statistics_test.rb
Labels: New Method

#80 i2-teamstats rival
  lib/team_statistics.rb
  test/team_statistics_test.rb
Labels: New Method, help wanted

#75 i2-average goals by season
  lib/game_statistics.rb
  test/game_statistics_test.rb
Labels: New Method

#81 i1 class methods
  lib/game.rb
  lib/game_team.rb
  lib/game_teams_collection.rb
  lib/games_collection.rb
  lib/stat_tracker.rb
  lib/team.rb
  lib/teams_collection.rb
  test/game_statistics_test.rb
  test/game_teams_collection_test.rb
  test/game_test.rb
  test/games_collection_test.rb
  test/teams_collection_test.rb
Labels: enhancement

#84 Simple cov
  .gitignore
  Gemfile
  Gemfile.lock
  test/game_statistics_test.rb
  test/game_team_test.rb
  test/game_test.rb
  test/league_statistics_test.rb
  test/stat_tracker_test.rb
  test/team_statistics_test.rb
  test/team_test.rb
  test/test_helper.rb
Labels: enhancement

#86 i3-Add mock and stub for season statistic
  test/stat_tracker_test.rb
  test/team_statistics_test.rb
Labels: enhancement

#88 Update game stat tests
  test/game_statistics_test.rb
Labels: enhancement

#89 Adds league stats games by team id mock
  lib/league_statistics.rb
  test/league_statistics_test.rb
Labels: New Method

#90 I3 game stat test
  lib/team_statistics.rb
  test/game_statistics_test.rb
Labels: bug

#83 i3-readme
  README.md
Labels: documentation
